### PR TITLE
feat: better debug output for CipherSuite and SslProtocol

### PR DESCRIPTION
**Pull request by robjtede**
tls_client example used to print:

```
negotiated cipher: CipherSuite(49199)
negotiated version: SslProtocol(8)
```

now prints:

```
negotiated cipher: CipherSuite(49199 = TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256)
negotiated version: SslProtocol(8 = TLS12)
```

### CODE REVIEW

**Review by djc — APPROVED** [review]

**Comment by djc** [comment]
I usually prefer to rebase (specifically, avoid having merge commits on main).

**Comment by robjtede** [comment]
Think I've got it set to not do that with squash merging. Will check when I'm back.

**Comment by djc** [comment]
Well, personally I also don't like squashing unnecessarily. But maybe I should just get out of the way and let you and @ComplexSpaces manage this.

**Comment by robjtede** [comment]
Just  in my experience gives PR authors freedom to push crap commits and have them cleaned up for "our" history.

**Comment by complexspaces** [comment]
FWIW, I would like to try rebasing only for a bit if you don't mind. Pushing contributors towards linear commits given the lower amount of traffic this crate usually has may be doable.

**Comment by robjtede** [comment]
So, with merge queues enabled, we don't actually require contributors to care about the linear history part, it will be handled for them when merging PRs (I'm pretty sure).

**Comment by djc** [comment]
Well, the merge queue configuration forces squashing or rebasing. So actually the merge queue mandates a single choice at the repo (actually, branch) whereas the non-merge queue approach leaves some per-PR flexibility.

**Pull request merged**
